version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --reload --workers 2 --host 0.0.0.0 --port 8000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ${LOCAL_FILE_DIR}:/usr/src/app/files
    ports:
      - 80:8000
